### ISSUE TITLE
No way to alter onComplete handler for autocomplete links

### ISSUE THREAD

**Issue by gmcinnes** [swiftype/swiftype-wordpress#29]
We would like clicks on the autocomplete links to open in a new window, a la `target="_blank"`  there's no way to do this at the moment, because the `onComplete` handler is hard coded here: 

https://github.com/swiftype/swiftype-wordpress/blob/dd82fdbb6f5d7a94885b6792fbea64372227a64e/assets/swiftype_config.js#L48

**Comment by qhoxie** [comment]
Fixed by #28
