### ISSUE TITLE
App search support

### ISSUE THREAD

**Issue by chrillep** [swiftype/swiftype-wordpress#56]
Are there any plans on adding app search support?
https://swiftype.com/documentation/app-search/getting-started
https://www.elastic.co/app-search/

**Comment by chrillep** [comment]
@afoucret @goodroot is this still in development?

**Comment by goodroot** [comment]
@chrillep Heya!

Unfortunately no, it is no longer under active development.

No current plans to add App Search support.

**Comment by chrillep** [comment]
cheers thanks for the answer. We went ahead and used the php package instead =)
